package com.lti.service;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;

import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailSender;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.stereotype.Service;

import com.lti.dao.AirlineOperationDao;
import com.lti.dao.GenericDao;
import com.lti.dto.BookingDT;
import com.lti.dto.SearchFlightsDT;
import com.lti.dto.TicketDT;
import com.lti.entity.Booking;
import com.lti.entity.Flight;
import com.lti.entity.Passenger;
import com.lti.entity.Payment;
import com.lti.entity.Seat;
import com.lti.entity.User;

@Service
public class AirlineServiceImpl implements AirlineService {

	@Autowired
	AirlineOperationDao airlineDao;

	@Autowired
	GenericDao dao;
	
	@Autowired
	MailSender mailSender;

	@Override
	public int registerUser(User user) {
		User updatedUser = (User) dao.save(user);
		String userId = String.valueOf(updatedUser.getUserId());
		SimpleMailMessage message = new SimpleMailMessage();

        message.setFrom("sonicairlines.autogenerated@gmail.com");
        message.setTo(user.getEmailId());
        message.setSubject("Succesfully Registered with Sonic Airlines");
        message.setText("You have been successfully registered. Your Registration ID is: "+userId);
        mailSender.send(message);
		
		return updatedUser.getUserId();
	}

	@Override
	public List<Flight> searchFlights(SearchFlightsDT searchFlightsDT) {
		return airlineDao.searchFlightOperation(searchFlightsDT);
	}

	@Override
	@Transactional
	public int addBooking(BookingDT bookingDT) {

		User user = new User();
		Flight flight = new Flight();
		Booking booking = new Booking();
		Passenger passenger = new Passenger();

		
		booking.setNoOfPassengers(bookingDT.getNoOfPassenger());
		booking.setCost(bookingDT.getCost());
		booking.setTicketMailingId(bookingDT.getEmailId());
		booking.setBookingDate(LocalDate.now());
		booking.setTravelClass(bookingDT.getTravelClass());

		user = dao.fetchById(User.class, bookingDT.getUserId());
		flight = dao.fetchById(Flight.class, bookingDT.getFlightId());

		System.out.println(flight);
		System.out.println(user);

		booking.setUser(user);
		booking.setFlight(flight);
		booking.setJourneyDate(flight.getJourneyDate());

		booking.setSource(flight.getSource());
		booking.setDestination(flight.getDestination());
		booking.setDeparture(flight.getDeparture());
		booking.setArrival(flight.getArrival());

		System.out.println(booking);
		Booking fetchedBooking = (Booking) dao.save(booking);
		int fetchedBookingId = fetchedBooking.getBookingId();
		System.out.println(fetchedBooking);
		
		int i = 0;
		HashSet<Passenger> passengers = new HashSet<Passenger>();
		for (Passenger p : bookingDT.getPassengerList()) {
			p.setBooking(fetchedBooking);
			p.setBookingStatus("Not Booked");
			p.setSeatId(bookingDT.getSeats().get(i));
			System.out.println(p.getSeatId());
			i++;
			airlineDao.addPassenger(p);
		}

		return fetchedBookingId;
	}

	@Override
	public void updateBooking(int bookinId) {
		List<Passenger> passengerList = airlineDao.fetchPassenger(bookinId);
		for (Passenger p : passengerList) {
			p.setBookingStatus("Confirmed");
			Seat seat = dao.fetchById(Seat.class, p.getSeatId());
			seat.setIsBooked("true");
			dao.save(seat);
			dao.save(p);
		}
		Booking booking = dao.fetchById(Booking.class, bookinId);
		int confirmedSeats = booking.getNoOfPassengers();

		Flight flight = airlineDao.fetchFlight(booking);

		if (booking.getTravelClass().equalsIgnoreCase("economy")) {
			flight.setEconomySeats(flight.getEconomySeats() - confirmedSeats);
		} else {
			flight.setBusinessSeats(flight.getBusinessSeats() - confirmedSeats);
		}
		flight = (Flight) dao.save(flight);

		Payment payment = new Payment();
		payment.setAmountPaid(booking.getCost());
		payment.setPaymentMode("Net Banking / UPI");
		payment.setBooking(booking);
		payment = (Payment) dao.save(payment);
	}
	
	

	@Override
	public TicketDT fetchTicket(int bookingId) {
		TicketDT ticket = airlineDao.fetchTicket(bookingId);
		return ticket;
	}

	@Override
	public double cancelTicket(int bookingId) {
		double refund = airlineDao.cancelTicket(bookingId);
		return refund;
	}

	@Override
	public List<Booking> fetchBookings(int userId) {
		return airlineDao.fetchBooking(userId);
	}

	@Override
	public List<Seat> fetchSeats(int flightId) {
		return airlineDao.fetchSeats(flightId);
		
	}

}
